[package]
name = "argocd-diff-preview"
version = "0.0.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="1.37.0",features = ["full"]}
base64 = "0.22.1"
serde = "1.0"
serde_yaml = "0.9"
serde_json = "1.0.117"
walkdir = "2.5.0"
schemars = "0.8.19"
structopt = { version = "0.3" }
regex = "1.10.4"
log = "0.4.21"
env_logger = "0.11.3"