site_name: Argo CD Diff Preview
repo_url: https://github.com/dag-andersen/argocd-diff-preview
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo-head.png
  favicon: assets/logo-head.png
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
  palette: 
    # Dark Mode
    scheme: slate
    primary: black
    accent: grey

nav:
- Overview: index.md
- Demo: demo.md
- How it works: how-it-works.md
- Getting started:
  - getting-started/github-actions-workflow.md
  - getting-started/gitlab-cicd.md
  - Local Installation: getting-started/installation.md
  - getting-started/custom-argo-cd-installation.md
  - Self-hosted Github Runners: getting-started/self-hosted-gh-runner.md
- Reusing clusters:
  - Connect to cluster with Argo CD pre-installed: reusing-clusters/connecting.md
  - Self-hosted runner connects with host cluster: reusing-clusters/self-hosted-gh-runner.md
  - Lockdown Mode: reusing-clusters/lockdown-mode.md
  - Openshift: reusing-clusters/openshift.md
- generated-applications.md
- Multi-repo: multi-repo.md
- application-selection.md
- Filter Output: filter-output.md
- Output formats: output.md
- All Options: options.md
- Troubleshooting: troubleshooting.md
- FAQ: faq.md

markdown_extensions:
  - toc:
      permalink: "ðŸ”—"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dag-andersen/argocd-diff-preview

copyright: Copyright &copy; 2024 Dag Bjerre Andersen
